-- TASK #71 FAZA B czesc 1: Story Bank PELNY (20 historii) + KANONICZNA BIOGRAFIA (05/07/2026).
-- Zrodlo: Notion 331c00c9...89a4 (fetch MCP 04/07). Idempotentne (kotwice page_id#sNN / brand_config k/v).
-- Probki #1/#2/#10 z Fazy A maja te same kotwice - NOT EXISTS = zero dubli.

INSERT INTO inspirations (source, content, brand, status, notion_page_id, metadata)
SELECT 'notion', '[Story Bank #1: 37 Faxes and One Sentence] Moved to Opole for a job that never materialized. 140zl/month after rent. Sent 37 faxes to kindergartens in Opole offering dance classes for children. One kindergarten replied - that reply launched a 20-year career. His mentor told him ''I will never respect you'' - broke his need for permission. | Key quote: Nobody is coming to save you. So move.', 'AGS', 'new', '331c00c90b9381eeb995cc757bfc89a4#s01', '{"meta_type": "story_bank", "story_number": 1, "title": "37 Faxes and One Sentence", "pillar": "Authenticity", "sensitivity": "MEDIUM", "key_quote": "Nobody is coming to save you. So move.", "seeds": ["800zl salary. 660zl rent. 140zl left. I didn''t have a backup plan. I had a fax machine.", "My mentor told me he''d never respect me. It was the most important thing anyone ever said."]}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM inspirations WHERE notion_page_id = '331c00c90b9381eeb995cc757bfc89a4#s01');

INSERT INTO inspirations (source, content, brand, status, notion_page_id, metadata)
SELECT 'notion', '[Story Bank #2: The Mentor Who Never Showed Up] The most important mentor was the one who never existed. From grandfather building furniture from scraps to Dr. Dziura who said: ''Take what you have, package it beautifully, and sell that.'' Those words became his operating system. | Key quote: Stop chasing what you wish you had. Take what you have, package it beautifully, and sell that.', 'AGS', 'new', '331c00c90b9381eeb995cc757bfc89a4#s02', '{"meta_type": "story_bank", "story_number": 2, "title": "The Mentor Who Never Showed Up", "pillar": "Simplicity", "sensitivity": "LOW", "key_quote": "Stop chasing what you wish you had. Take what you have, package it beautifully, and sell that.", "seeds": ["My thesis advisor rejected 80% of my work. Then gave me the only business advice I''ve ever needed.", "At 45 I still use the same OS: package what you have, sell it, learn with the revenue."]}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM inspirations WHERE notion_page_id = '331c00c90b9381eeb995cc757bfc89a4#s02');

INSERT INTO inspirations (source, content, brand, status, notion_page_id, metadata)
SELECT 'notion', '[Story Bank #3: The Night a Champion Cried in Paris] Polish dance champion humbled in Paris by a street dancer who trained every discipline. Cried in hotel room realizing his trophies were earned inside a small box. Returned committed to never stop learning. | Key quote: Your trophies can become the walls of your cage.', 'AGS', 'new', '331c00c90b9381eeb995cc757bfc89a4#s03', '{"meta_type": "story_bank", "story_number": 3, "title": "The Night a Champion Cried in Paris", "pillar": "Authenticity", "sensitivity": "LOW", "key_quote": "Your trophies can become the walls of your cage.", "seeds": ["I went to Paris as a national champion. I came back as a beginner.", "The founder who thinks their first win means they''ve figured it out - I was that guy."]}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM inspirations WHERE notion_page_id = '331c00c90b9381eeb995cc757bfc89a4#s03');

INSERT INTO inspirations (source, content, brand, status, notion_page_id, metadata)
SELECT 'notion', '[Story Bank #4: The Audiobook on the Highway] In 2019, during a long drive as his world fell apart, first real encounter with self-development (Brian Tracy). Sparked a chain reaction of learning. At 38, decided to become the mentor he never had. | Key quote: Every disaster carries a lesson. But you have to do the homework.', 'AGS', 'new', '331c00c90b9381eeb995cc757bfc89a4#s04', '{"meta_type": "story_bank", "story_number": 4, "title": "The Audiobook on the Highway", "pillar": "Simplicity", "sensitivity": "LOW", "key_quote": "Every disaster carries a lesson. But you have to do the homework.", "seeds": ["I wasted years. Then I pressed play on one audiobook and everything started to change.", "I stopped scrolling garbage and started feeding my brain on purpose."]}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM inspirations WHERE notion_page_id = '331c00c90b9381eeb995cc757bfc89a4#s04');

INSERT INTO inspirations (source, content, brand, status, notion_page_id, metadata)
SELECT 'notion', '[Story Bank #5: Three Legs, Zero Left] Fourth festival bankrupted him (200K debt). Lost money, health, marriage. Stood on a bridge. Children were the reason he stepped back. Ola offered a room: ''You cook.'' Rebuilt from that floor. | Key quote: Nobody is going to save you. But someone might say ''you cook'' - and that''s enough to start.', 'AGS', 'new', '331c00c90b9381eeb995cc757bfc89a4#s05', '{"meta_type": "story_bank", "story_number": 5, "title": "Three Legs, Zero Left", "pillar": "Authenticity", "sensitivity": "HIGH", "key_quote": "Nobody is going to save you. But someone might say ''you cook'' - and that''s enough to start.", "seeds": ["Life stands on three legs: money, health, love. I lost all three at once.", "One person called and said: ''You can be my roommate. You cook.''"]}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM inspirations WHERE notion_page_id = '331c00c90b9381eeb995cc757bfc89a4#s05');

INSERT INTO inspirations (source, content, brand, status, notion_page_id, metadata)
SELECT 'notion', '[Story Bank #6: Don''t Look in Your Boss''s Wallet] Discovered his trainer charged 350zl/person while paying dancers 100zl/weekend. A musician set him straight: you agreed to the terms. Years later, his own employees did the same to him. | Key quote: The moment you start resenting someone else''s margin, you''ve stopped focusing on building your own.', 'AGS', 'new', '331c00c90b9381eeb995cc757bfc89a4#s06', '{"meta_type": "story_bank", "story_number": 6, "title": "Don''t Look in Your Boss''s Wallet", "pillar": "Simplicity", "sensitivity": "LOW", "key_quote": "The moment you start resenting someone else''s margin, you''ve stopped focusing on building your own.", "seeds": ["A stranger on a ferry shook me and said: ''Don''t look in your boss''s wallet.''", "Nobody puts this on a poster: stop complaining about what others earn."]}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM inspirations WHERE notion_page_id = '331c00c90b9381eeb995cc757bfc89a4#s06');

INSERT INTO inspirations (source, content, brand, status, notion_page_id, metadata)
SELECT 'notion', '[Story Bank #7: Empty Shelves, Full Imagination] Born 1980, communist Poland. No TV, no internet. Creativity born from scarcity. Today applies same principle: fewer toys = more creative kids. | Key quote: Give a child everything and they''ll play with nothing. Give them nothing and they''ll build a world.', 'AGS', 'new', '331c00c90b9381eeb995cc757bfc89a4#s07', '{"meta_type": "story_bank", "story_number": 7, "title": "Empty Shelves, Full Imagination", "pillar": "Simplicity", "sensitivity": "LOW", "key_quote": "Give a child everything and they''ll play with nothing. Give them nothing and they''ll build a world.", "seeds": ["I grew up in communist Poland. The worst punishment? Not being allowed outside.", "My grandmother arranged the table so you couldn''t see what was missing."]}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM inspirations WHERE notion_page_id = '331c00c90b9381eeb995cc757bfc89a4#s07');

INSERT INTO inspirations (source, content, brand, status, notion_page_id, metadata)
SELECT 'notion', '[Story Bank #8: The Eiffel Tower Ticket] Broke student in Paris. Pan Rysio bought him an Eiffel Tower ticket without conditions. That act opened something. Years later, Tomasz takes homeless people to stores to buy food. | Key quote: When you''ve been to the top of the tower, buy someone else''s ride up.', 'AGS', 'new', '331c00c90b9381eeb995cc757bfc89a4#s08', '{"meta_type": "story_bank", "story_number": 8, "title": "The Eiffel Tower Ticket", "pillar": "Authenticity", "sensitivity": "LOW", "key_quote": "When you''ve been to the top of the tower, buy someone else''s ride up.", "seeds": ["A man I barely knew bought me a ticket because he remembered what first times feel like.", "I never give money to strangers. But I''ll take you to a store and fill your basket."]}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM inspirations WHERE notion_page_id = '331c00c90b9381eeb995cc757bfc89a4#s08');

INSERT INTO inspirations (source, content, brand, status, notion_page_id, metadata)
SELECT 'notion', '[Story Bank #9: The Darkroom and the Gimbal] Grandfather taught photography with a Soviet camera. Abandoned for 20 years. Pandemic grant funded a camera. Reconnected with the obsession. Brutally self-critical - same engine that drives growth. | Key quote: The gap between where you are and where you want to be isn''t frustration. It''s fuel.', 'AGS', 'new', '331c00c90b9381eeb995cc757bfc89a4#s09', '{"meta_type": "story_bank", "story_number": 9, "title": "The Darkroom and the Gimbal", "pillar": "Authenticity", "sensitivity": "LOW", "key_quote": "The gap between where you are and where you want to be isn''t frustration. It''s fuel.", "seeds": ["My grandfather taught me photography with a Soviet camera and a darkroom. Thirty years later, I picked up a gimbal.", "The pandemic took my revenue. A government grant gave me a camera."]}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM inspirations WHERE notion_page_id = '331c00c90b9381eeb995cc757bfc89a4#s09');

INSERT INTO inspirations (source, content, brand, status, notion_page_id, metadata)
SELECT 'notion', '[Story Bank #10: The Full Circle Pivot] Studied Electronics and Telecommunications; master''s thesis: intelligent building management system (client-server). Declined a PhD. Worked in a building materials warehouse while teaching dance after hours. When dance outearned the salary, opened a studio - Plan B that became 20 years. Now returning to systems with AI at 45. He was a programmer and systems architect FIRST. Engineer''s mind, artist''s soul. | Key quote: The shaking doesn''t mean you''re not ready. It means you''re about to grow.', 'AGS', 'new', '331c00c90b9381eeb995cc757bfc89a4#s10', '{"meta_type": "story_bank", "story_number": 10, "title": "The Full Circle Pivot", "pillar": "Visibility", "sensitivity": "MEDIUM", "key_quote": "The shaking doesn''t mean you''re not ready. It means you''re about to grow.", "seeds": ["My master''s thesis was a smart building management system. Client-server architecture. 25 years later I''m building AI agent orchestras. The circle closed.", "I was a programmer first. Dance was supposed to be the side hustle. The side hustle won for 20 years. Now the engineer is back.", "Choreography is architecture. A formation of 12 dancers is a distributed system."]}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM inspirations WHERE notion_page_id = '331c00c90b9381eeb995cc757bfc89a4#s10');

INSERT INTO inspirations (source, content, brand, status, notion_page_id, metadata)
SELECT 'notion', '[Story Bank #11: Jakos To Bedzie] Polish phrase = ''it''ll work out somehow''. His OS, worked 95% when paired with action. Pandemic hit, dance school shut down, youngest daughter 6 months old, last money left. At 40 bought a marketing course and started immediately. Rebuilt mind before business. | Key quote: Jakos to bedzie, ale tylko jesli ja to zrobie.', 'AGS', 'new', '331c00c90b9381eeb995cc757bfc89a4#s11', '{"meta_type": "story_bank", "story_number": 11, "title": "Jakos To Bedzie", "pillar": "Authenticity", "sensitivity": "MEDIUM", "key_quote": "Jakos to bedzie, ale tylko jesli ja to zrobie.", "seeds": ["Pandemic. Dance school closed. Baby daughter. Last money. I bought a marketing course. Not because I could afford it. Because I couldn''t afford to stay the same.", "Optimism without action is delusion. Optimism with action is prophecy."]}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM inspirations WHERE notion_page_id = '331c00c90b9381eeb995cc757bfc89a4#s11');

INSERT INTO inspirations (source, content, brand, status, notion_page_id, metadata)
SELECT 'notion', '[Story Bank #12: 200,000 Zloty I Didn''t Have] Fourth Opole Dance Festival - 37 international artists, 12 rooms. Didn''t have the budget. Result: 200K debt, threatening calls, marriage end. Audience loved it. He was drowning. | Key quote: Don''t confuse ambition with a plan.', 'AGS', 'new', '331c00c90b9381eeb995cc757bfc89a4#s12', '{"meta_type": "story_bank", "story_number": 12, "title": "200,000 Zloty I Didn''t Have", "pillar": "Simplicity", "sensitivity": "MEDIUM", "key_quote": "Don''t confuse ambition with a plan.", "seeds": ["I organized a festival for 37 international artists. The audience loved it. I went 200,000zl into debt.", "The most expensive business school had no campus, no diploma. Just threats and 200K debt."]}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM inspirations WHERE notion_page_id = '331c00c90b9381eeb995cc757bfc89a4#s12');

INSERT INTO inspirations (source, content, brand, status, notion_page_id, metadata)
SELECT 'notion', '[Story Bank #13: The Donkey Who Wouldn''t Fall] Core strengths: stubbornness, creativity, intuition, speed. Something breaks - hands building before brain finishes processing. Pattern saved him 3 times. Now with AI as multiplier. | Key quote: Luck shows up when you refuse to stop moving.', 'AGS', 'new', '331c00c90b9381eeb995cc757bfc89a4#s13', '{"meta_type": "story_bank", "story_number": 13, "title": "The Donkey Who Wouldn''t Fall", "pillar": "Authenticity", "sensitivity": "LOW", "key_quote": "Luck shows up when you refuse to stop moving.", "seeds": ["I''m stubborn like a donkey. Three times I lost everything. Three times the same engine pulled me out.", "I don''t sit with problems. Something breaks and my hands are already building."]}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM inspirations WHERE notion_page_id = '331c00c90b9381eeb995cc757bfc89a4#s13');

INSERT INTO inspirations (source, content, brand, status, notion_page_id, metadata)
SELECT 'notion', '[Story Bank #14: Dancing on a Razor Blade] Everyone advised safety. He took the safe job and nearly starved. Dance teacher training piece titled ''Dance on a Razor Blade'' - performed in silence. Written in twenties, became literal life philosophy. | Key quote: You can''t stand still on a razor. You can only dance.', 'AGS', 'new', '331c00c90b9381eeb995cc757bfc89a4#s14', '{"meta_type": "story_bank", "story_number": 14, "title": "Dancing on a Razor Blade", "pillar": "Authenticity", "sensitivity": "LOW", "key_quote": "You can''t stand still on a razor. You can only dance.", "seeds": ["Everyone told me to get a safe job. It paid 800zl a month and nearly starved me.", "A safe life would have cost me everything I am."]}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM inspirations WHERE notion_page_id = '331c00c90b9381eeb995cc757bfc89a4#s14');

INSERT INTO inspirations (source, content, brand, status, notion_page_id, metadata)
SELECT 'notion', '[Story Bank #15: The Space Between Intention and Perception] After festival debts, became known as someone who doesn''t pay. Real mistake: wrapping bad news in soft language. Lesson: clarity is the highest form of respect. | Key quote: Clarity is the highest form of respect.', 'AGS', 'new', '331c00c90b9381eeb995cc757bfc89a4#s15', '{"meta_type": "story_bank", "story_number": 15, "title": "The Space Between Intention and Perception", "pillar": "Simplicity", "sensitivity": "HIGH", "key_quote": "Clarity is the highest form of respect.", "seeds": ["I wrapped bad news in soft language and it made me look like a liar.", "Integrity isn''t about being perfect. It''s about being clear."]}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM inspirations WHERE notion_page_id = '331c00c90b9381eeb995cc757bfc89a4#s15');

INSERT INTO inspirations (source, content, brand, status, notion_page_id, metadata)
SELECT 'notion', '[Story Bank #16: The Hole You Don''t Furnish] Recurring challenge = money. Not poverty but constant grind. Refuses to let kids see the hole. Strategy: learn, apply, earn, repeat. Building a garden on top of a crater. | Key quote: The temptation when you''re broke isn''t spending. It''s settling.', 'AGS', 'new', '331c00c90b9381eeb995cc757bfc89a4#s16', '{"meta_type": "story_bank", "story_number": 16, "title": "The Hole You Don''t Furnish", "pillar": "Authenticity", "sensitivity": "MEDIUM", "key_quote": "The temptation when you''re broke isn''t spending. It''s settling.", "seeds": ["I''m not filling a hole. I''m building a garden on top of one. My kids only see the garden.", "When you''re walking through hell, don''t stop. And don''t furnish the place."]}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM inspirations WHERE notion_page_id = '331c00c90b9381eeb995cc757bfc89a4#s16');

INSERT INTO inspirations (source, content, brand, status, notion_page_id, metadata)
SELECT 'notion', '[Story Bank #17: The Pivot That''s Happening Right Now] Mid-pivot from dance to AI. This one doesn''t have a happy ending yet. Master''s thesis 25 years ago = smart building systems. Dance = 20-year detour. Now returning with AI. Knees shaking. | Key quote: The scary part is staying in a life that''s too small for who you''ve become.', 'AGS', 'new', '331c00c90b9381eeb995cc757bfc89a4#s17', '{"meta_type": "story_bank", "story_number": 17, "title": "The Pivot That''s Happening Right Now", "pillar": "Visibility", "sensitivity": "LOW", "key_quote": "The scary part is staying in a life that''s too small for who you''ve become.", "seeds": ["I''m not pivoting away from something broken. I''m pivoting toward something I was always meant to build.", "I don''t have a success story yet. I''m writing it in real time."]}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM inspirations WHERE notion_page_id = '331c00c90b9381eeb995cc757bfc89a4#s17');

INSERT INTO inspirations (source, content, brand, status, notion_page_id, metadata)
SELECT 'notion', '[Story Bank #18: The Man Who Doesn''t Balance] Doesn''t have work-life balance, doesn''t pretend to. Strategy: build a life where work doesn''t feel like work. At 11 PM, cold-messaging on LinkedIn. Traction recharges him. | Key quote: Balance is for people who hate their Mondays.', 'AGS', 'new', '331c00c90b9381eeb995cc757bfc89a4#s18', '{"meta_type": "story_bank", "story_number": 18, "title": "The Man Who Doesn''t Balance", "pillar": "Visibility", "sensitivity": "LOW", "key_quote": "Balance is for people who hate their Mondays.", "seeds": ["It''s 11 PM. Wife pregnant, kids asleep, I''m cold-messaging strangers on LinkedIn. That''s not hustle porn. That''s a man who found work that doesn''t feel like work.", "I don''t recharge by resting. I recharge by seeing traction."]}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM inspirations WHERE notion_page_id = '331c00c90b9381eeb995cc757bfc89a4#s18');

INSERT INTO inspirations (source, content, brand, status, notion_page_id, metadata)
SELECT 'notion', '[Story Bank #19: The Wedding Where Nobody Stood Up] Married wrong woman knowing it at the altar. Hoped Ola would object. She didn''t. Years in loveless marriage. Divorce, bankruptcy, bridge - all flowed from choosing comfort over truth. Now married to Ola. | Key quote: If you''re standing at the altar hoping someone will save you from your own decision - you already have your answer.', 'AGS', 'new', '331c00c90b9381eeb995cc757bfc89a4#s19', '{"meta_type": "story_bank", "story_number": 19, "title": "The Wedding Where Nobody Stood Up", "pillar": "Authenticity", "sensitivity": "HIGH", "key_quote": "If you''re standing at the altar hoping someone will save you from your own decision - you already have your answer.", "seeds": ["I chose comfort over love and called it being practical.", "The right person was in the room the whole time."]}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM inspirations WHERE notion_page_id = '331c00c90b9381eeb995cc757bfc89a4#s19');

INSERT INTO inspirations (source, content, brand, status, notion_page_id, metadata)
SELECT 'notion', '[Story Bank #20: The Smell of Cut Grass] Success evolved: trophies (20), business (30), food on table (39), peace and choice (45). Wants to be a multimillionaire - money as tool, not destination. Real success = ability to choose. | Key quote: Success is the ability to choose, not the obligation to hustle.', 'AGS', 'new', '331c00c90b9381eeb995cc757bfc89a4#s20', '{"meta_type": "story_bank", "story_number": 20, "title": "The Smell of Cut Grass", "pillar": "Simplicity", "sensitivity": "LOW", "key_quote": "Success is the ability to choose, not the obligation to hustle.", "seeds": ["At 20, success was a trophy. At 30, a business. At 39, food on the table. At 45, it''s the smell of cut grass.", "My kids don''t need a father who''s always catching up. They need a father who''s present."]}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM inspirations WHERE notion_page_id = '331c00c90b9381eeb995cc757bfc89a4#s20');

-- kanoniczna biografia -> brand_config (doktryna nadrzedna; klucz/wartosc wzorcem voice_bible)
INSERT INTO brand_config (brand_id, config_key, config_value, version, updated_by, updated_at)
VALUES ('AGS', 'canonical_bio', 'KANONICZNA BIOGRAFIA (14/05/2026) - jesli jakikolwiek dokument mowi inaczej, TEN wygrywa. Tomasz to INZYNIER ktory wrocil do korzeni, NIE 'choreograf ktory nauczyl sie AI'. PRAWDA: ukonczyl Elektronike i Telekomunikacje (magisterka: system zarzadzania inteligentnym budynkiem, architektura klient-serwer); mial sie doktoryzowac - ODMOWIL; pracowal na etacie w hurtowni budowlanej; zajecia taneczne prowadzil po godzinach jako dodatkowy dochod; otworzyl studio dopiero gdy taniec zarabial wiecej niz etat; taniec = Plan B ktory stal sie 20-letnia kariera; AI = POWROT do korzeni - byl programista i architektem systemow OD POCZATKU. NIGDY: 'dance teacher who learned AI', 'choreographer who discovered systems', 'sent faxes to dance studios' (faxy byly do PRZEDSZKOLI - oferta zajec dla dzieci, historia #1). POPRAWNIE: 'systems architect who spent 20 years on a dance floor', 'the engineer came back', 'returned to systems architecture at 45', 'engineer''s mind, artist''s soul' (inzynier pierwszy). Sensitivity: HIGH stories #5/#15/#19 approved, uzywac z intencja.', 1, 'task-71-fazaB', NOW())
ON CONFLICT (brand_id, config_key) DO UPDATE SET config_value=EXCLUDED.config_value,
  version=brand_config.version+1, updated_by=EXCLUDED.updated_by, updated_at=NOW();

-- WERYFIKACJA:
SELECT COUNT(*) AS story_bank_rows FROM inspirations WHERE notion_page_id LIKE '331c00c90b9381eeb995cc757bfc89a4#%';
SELECT config_key, version, length(config_value) AS len FROM brand_config WHERE config_key='canonical_bio';
